### PR TITLE
Fix stop delay and threading error

### PR DESCRIPTION
**Pull request by Chapoly1305**
For Issue https://github.com/NordicSemiconductor/nRF-Sniffer-for-802.15.4/issues/58
Tested on Macbook and Ubuntu 22.04, the script is now responsive when press stop button without giving a pop-up error.

The previous pull request (https://github.com/NordicSemiconductor/nRF-Sniffer-for-802.15.4/pull/64) was not merged but the head brach was deleted by accident. Creating a new pull request with identical modification.

### CODE REVIEW

**Comment by e-rk** [comment]
I have gave the change a try and it looks like there is a problem with stopping the capture on Linux. When the `Stop capturing packets` button is clicked, the extcap does not close the serial port and the process does not terminate.
Unfortunately the code around the cleanup is very flaky and difficult to get right on every operating system.

**Comment by Chapoly1305** [comment]
@e-rk Hi, thanks for the test. From your description, it sounds you have tested on the wrong file? Your description matches exactly the old script, and that's why I modified the previous script. So I kindly ask your favor to try again, ensure you replaced the old file and are using the modified script. If you may, remove the existing files from local and global, then add this new python file. Thanks.

image

**Comment by e-rk** [comment]
I have re-tested again on Wireshark v3.2.3 on Ubuntu 20.04 and yes, that's the problem I'm seeing with this change unfortunately. Maybe it's due to the difference in Wireshark version. I tried to test with the v4.4.1-1 on Archlinux, but that version seems to fail for some different reason during initialization. I'll try to investigate this on my side.

**Comment by tofurky** [comment]
This seems to be working on Ubuntu 24.04 / Wireshark 4.2.2 - thanks!

Before:
```
...
 ** (wireshark:356127) 12:52:00.730424 [Capture MESSAGE] -- Capture Stop ...
 ** (wireshark:356127) 12:52:30.814195 [Capture MESSAGE] -- Capture stopped.
 ** (wireshark:356127) 12:52:30.814213 [Capture WARNING] ./ui/capture.c:722 -- capture_input_closed(): Error from extcap pipe: 2024-12-21 12:52:10,730 [ERROR] Failed to stop thread Thread-1 (control_reader)
 ```
 After:
 ```
...
 ** (wireshark:356472) 12:53:09.737700 [Capture MESSAGE] -- Capture Stop ...
 ** (wireshark:356472) 12:53:10.749264 [Capture MESSAGE] -- Capture stopped.
 ** (wireshark:356472) 12:53:10.749279 [Capture WARNING] ./ui/capture.c:722 -- capture_input_closed(): 
 ```

**Comment by tofurky** [comment]
Also, BTW @Chapoly1305 GitHub is saying something about CLA needing to be signed. Unsure if that'd speed up the review/merge.

**Comment by Chapoly1305** [comment]
@tofurky 
Congrats on having it working. 
Thanks for the heads-up on the signing. I actually have signed the CLA but I think I have put some random Email address for the commit. I will create another MR.

**Pull request closed without merging**
