### PR TITLE
PCAP on socket, rstText in docstring, refactor.

### PR DESCRIPTION
**Pull request by phe-sto**
* New queue sending PCAP through a socket at connection.
* Docstring a rstText for integration in sphinx documentation.
* Add method listing port out of a Wireshark specific one.
* Refactor with AutoPep8.
* Refactor only importing desired objects instead of modules.
* Refactor unused parameters and arguments

Otherwise I tried to keep the spirit of the original library.

### CODE REVIEW

**Comment by e-rk** [comment]
Thank you for this pull request. 
Unfortunately we will not have the time to look at it in 2019. We will get back to you after the new year.
In the meantime, can you please try resolving problems with the CLA? Probably email in the commit does not match the email in your Github profile.

Thank you for your patience.

**Comment by phe-sto** [comment]
Hi Rafal,

 

Thank you for your feedback.


I signed the CLA, I doubled check the page says You have signed the CLA for NordicSemiconductor/nRF-Sniffer-for-802.15.4.


Enjoy your Christmas, we will get in touch later.


Best regards,


Christophe


 

De : Rafał Kuźnia <notifications@github.com> 
Envoyé : lundi 16 décembre 2019 12:31
À : NordicSemiconductor/nRF-Sniffer-for-802.15.4 <nRF-Sniffer-for-802.15.4@noreply.github.com>
Cc : PapIT <christophe.brun.papit@gmail.com>; Author <author@noreply.github.com>
Objet : Re: [NordicSemiconductor/nRF-Sniffer-for-802.15.4] PCAP on socket, rstText in docstring, refactor. (#38)

 

Thank you for this pull request.
Unfortunately we will not have the time to look at it in 2019. We will get back to you after the new year.
In the meantime, can you please try resolving problems with the CLA? Probably email in the commit does not match the email in your Github profile.

Thank you for your patience.

**Comment by hubertmis** [comment]
@phe-sto, could you describe _New queue sending PCAP through a socket at connection_ functionality? I'm curious if it is similar to the feature provided in #39 or something else.

**Comment by phe-sto** [comment]
@hubertmis no it is different. The purpose is to send a pcap through a socket. With this stream a simple client can write the file. For instance a test running whilst sniffing the network, producing a trace for each test.

**Comment by phe-sto** [comment]
Without wanting to put pressure, just for the love of 802.15.4  :smiley:, can we go further with this PR. It is safe, I am using it everyday since several months now.

Best regards

**Comment by hubertmis** [comment]
@phe-sto , I'm sorry for the late response. Ownership of this project is being moved and for some time nobody was maintaining it.
Our vision for this project is to keep simple feature set to enable Wireshark users to use nRF devices as 802.15.4 sniffers. We don't want to invest in additional features like a socket connection. Such additional features make this project harder to maintain. Because of that I'm closing this PR.
I'm encouraging you to keep your feature-rich fork alive. Let community decide which version is more desirable.

**Pull request closed without merging**
